name: Production CI

on:
  push:
    branches: [master]
    tags:
      - "v*" # This will trigger the workflow for any tag starting with 'v'
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  production-build:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      tag_prefix: ""
      branch: ${{ github.ref_name }}
