name: Production CI

on:
  push:
    tags:
      - "v*" # This will trigger the workflow for any tag starting with 'v'
permissions:
  contents: read
  packages: write

jobs:
  production-build:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      tag_prefix: ""
      branch: ${{ github.ref_name }}
