name: Production CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  production-build:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      tag_prefix: ""
      branch: "master"
