name: Staging CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

permissions:
  contents: read
  packages: write

jobs:
  staging-build:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      tag_prefix: 'staging-'
      branch: 'staging'